import mongoose from "mongoose";

const extraChargesSchema = new mongoose.Schema(
    {
        accountCode: { type: String, required: true },
        awbNo: { type: String, required: true },
        referenceNo: String,
        runDate: String,
        origin: String,
        sector: String,
        destination: String,
        customer: String,
        accountBalance: Number,
        company: String,
        consignor: String,
        "consignor-addressLine1": String,
        "consignor-addressLine2": String,
        "consignor-pincode": String,
        "consignor-city": String,
        "consignor-state": String,
        "consignor-telephone": String,
        "consignor-idType": String,
        "consignor-idNumber": String,
        consignee: String,
        "consignee-addressLine1": String,
        "consignee-addressLine2": String,
        "consignee-zipcode": String,
        "consignee-city": String,
        "consignee-state": String,
        "consignee-telephone": String,
        "consignee-emailID": String,
        network: String,
        networkName: String,
        service: String,
        volWt: Number,
        volDisc: Number,
        fwdNumber: String,
        shipmentType: String,
        pcs: Number,
        actualWt: Number,
        chargableWt: Number,
        payment: String,
        currencys: String,
        invoiceValue: Number,
        content: [String],
        invoice: String,
        operationRemark: String,
        isHold: Boolean,
        holdReason: String,
        otherHoldReason: String,
        mawbNo: String,
        runNo: String,
        bag: String,
        clubNo: String,
        alMawb: String,
        flight: String,
        obc: String,
        basicAmount: Number,
        manualAmount: Number,
        cashRecvAmount: Number,
        balanceAmount: Number,
        handlingAmount: Number,
        miscChg: Number,
        miscChgReason: String,
        duty: Number,
        overWtHandling: Number,
        hikeAmt: String,
        fuelPercentage: Number,
        fuelAmt: Number,
        discount: Number,
        discountAmt: Number,
        sgst: Number,
        cgst: Number,
        igst: Number,
        grandTotal: Number,
        currency: String,
        billNo: String,
        manifestNo: String,
        baseGrandTotal: Number,

        invoiceContent: { type: mongoose.Schema.Types.Mixed },
        volumeContent: { type: mongoose.Schema.Types.Mixed },
    },
    { timestamps: true }
);

const ExtraCharges =
    mongoose.models.ExtraCharges || mongoose.model("ExtraCharges", extraChargesSchema);

export default ExtraCharges;
